# Generated by Django 2.2.4 on 2019-08-23 06:56

from django.db import migrations, models
import django.db.models.deletion
import pipeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=32, unique=True, verbose_name='模板ID')),
                ('name', models.CharField(default='default_template', max_length=128, verbose_name='模板名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('editor', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改者')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('has_subprocess', models.BooleanField(default=False, verbose_name='是否含有子流程')),
                ('is_deleted', models.BooleanField(default=False, help_text='表示当前模板是否删除', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'Pipeline模板',
                'verbose_name_plural': 'Pipeline模板',
                'ordering': ['-edit_time'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5sum', models.CharField(max_length=32, unique=True, verbose_name='快照字符串的md5sum')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data', pipeline.models.CompressJSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '模板快照',
                'verbose_name_plural': '模板快照',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCurrentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(db_index=True, max_length=32, verbose_name='模板ID')),
                ('current_version', models.CharField(max_length=32, verbose_name='快照字符串的md5')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor_template_id', models.CharField(db_index=True, max_length=32, verbose_name='根模板ID')),
                ('descendant_template_id', models.CharField(max_length=32, verbose_name='子流程模板ID')),
                ('subprocess_node_id', models.CharField(max_length=32, verbose_name='子流程节点 ID')),
                ('version', models.CharField(max_length=32, verbose_name='快照字符串的md5')),
            ],
        ),
        migrations.CreateModel(
            name='TreeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', pipeline.models.CompressJSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(db_index=True, max_length=32, verbose_name='快照字符串的md5')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Snapshot', verbose_name='模板数据 ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.PipelineTemplate', verbose_name='模板 ID')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=97, unique=True, verbose_name='方案唯一ID')),
                ('name', models.CharField(max_length=64, verbose_name='方案名称')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('data', pipeline.models.CompressJSONField(verbose_name='方案数据')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.PipelineTemplate', verbose_name='对应模板 ID')),
            ],
        ),
        migrations.AddField(
            model_name='pipelinetemplate',
            name='snapshot',
            field=models.ForeignKey(on_delete=None, related_name='snapshot_templates', to='pipeline.Snapshot', verbose_name='模板结构数据'),
        ),
        migrations.CreateModel(
            name='PipelineInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=32, unique=True, verbose_name='实例ID')),
                ('name', models.CharField(default='default_instance', max_length=128, verbose_name='实例名称')),
                ('creator', models.CharField(blank=True, max_length=32, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.CharField(blank=True, max_length=32, verbose_name='执行者')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_started', models.BooleanField(default=False, verbose_name='是否已经启动')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否已经完成')),
                ('is_deleted', models.BooleanField(default=False, help_text='表示当前实例是否删除', verbose_name='是否已经删除')),
                ('execution_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_snapshot_instances', to='pipeline.Snapshot', verbose_name='用于实例执行的结构数据')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_instances', to='pipeline.Snapshot', verbose_name='实例结构数据，指向实例对应的模板的结构数据')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.PipelineTemplate', verbose_name='Pipeline模板')),
                ('tree_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_info_instances', to='pipeline.TreeInfo', verbose_name='提前计算好的一些流程结构数据')),
            ],
            options={
                'verbose_name': 'Pipeline实例',
                'verbose_name_plural': 'Pipeline实例',
                'ordering': ['-create_time'],
            },
        ),
    ]
