# Generated by Django 2.2.4 on 2019-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0010_auto_20190304_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentexecutedata',
            name='subprocess_stack',
            field=models.TextField(default='[]', help_text='JSON 格式的列表', verbose_name='子流程堆栈'),
        ),
        migrations.AlterField(
            model_name='componentintemplate',
            name='subprocess_stack',
            field=models.TextField(default='[]', help_text='JSON 格式的列表', verbose_name='子流程堆栈'),
        ),
    ]
